import { ProgressBar } from '@/components/global';
import { QueryProvider } from '@/components/provider/query-provider';
import { NextAuthSessionProvider } from '@/components/provider/session-provider';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - PUPRIS',
    default: 'PUPRIS',
  },
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/favicon/favicon.ico',
      type: 'image/ico',
    },
    shortcut: ['/favicon/favicon-32x32.png'],
    apple: [{ url: '/favicon/apple-touch-icon.png' }],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <QueryProvider>
            <ProgressBar />
            {children}
            <Toaster />
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
