"""2 edit

Revision ID: 01f2e606e328
Revises: f2ff00a00ec4
Create Date: 2023-12-27 18:10:56.798498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '01f2e606e328'
down_revision: Union[str, None] = 'f2ff00a00ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navigation_role', sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('navigation_role', 'section')
    op.drop_column('navigation_role', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navigation_role', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('navigation_role', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('navigation_role', 'class_id')
    # ### end Alembic commands ###
