"""2

Revision ID: 04b6c4be026d
Revises: c5cbca0ec3d3
Create Date: 2023-11-10 11:18:23.464588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b6c4be026d'
down_revision: Union[str, None] = 'c5cbca0ec3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('research_paper_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'authors', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'research_paper_id')
    # ### end Alembic commands ###
