"""new fields

Revision ID: 0d5e8541ff4a
Revises: 2ee320eaea26
Create Date: 2023-10-31 22:30:27.957994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0d5e8541ff4a'
down_revision: Union[str, None] = '2ee320eaea26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('student', sa.Column('course', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'course')
    op.drop_column('student', 'section')
    op.drop_column('student', 'year')
    # ### end Alembic commands ###
