"""copyright2

Revision ID: 14d46f95aeaa
Revises: 7be7eaa6522f
Create Date: 2023-11-24 16:43:11.720817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '14d46f95aeaa'
down_revision: Union[str, None] = '7be7eaa6522f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copyright',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('co_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affidavit_co_ownership', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joint_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_sheet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recordal_slip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acknowledgement_receipt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recordal_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ureb_18', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('journal_publication', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('copyright_manuscript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['research_paper_id'], ['research_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copyright')
    # ### end Alembic commands ###
