"""revision

Revision ID: 3eb9b26b209b
Revises: 15a91d10f06f
Create Date: 2023-11-05 10:23:54.982671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb9b26b209b'
down_revision: Union[str, None] = '15a91d10f06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('research_adviser', sa.Integer(), nullable=True))
    op.drop_constraint('research_papers_adviser_id_fkey', 'research_papers', type_='foreignkey')
    op.drop_column('research_papers', 'adviser_id')  # Specify the column name to drop
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('adviser_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('research_papers_adviser_id_fkey', 'research_papers', 'users', ['adviser_id'], ['id'])
    op.drop_column('research_papers', 'research_adviser')
    # ### end Alembic commands ###
