"""new tables

Revision ID: 3f78fd13d719
Revises: e655cd293de6
Create Date: 2023-11-09 09:52:16.724047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3f78fd13d719'
down_revision: Union[str, None] = 'e655cd293de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_papers_status',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal', sa.Boolean(), nullable=False),
    sa.Column('under_review', sa.Boolean(), nullable=False),
    sa.Column('research_protocol', sa.Boolean(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('research_adviser', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_status_id'], ['research_papers_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('research_papers', sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('research_papers', sa.Column('research_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('research_papers', sa.Column('submitted_date', sa.DateTime(), nullable=False))
    op.add_column('research_papers', sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('research_papers', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('research_papers', 'created_at')
    op.drop_column('research_papers', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('research_papers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('research_papers', 'file_path')
    op.drop_column('research_papers', 'keywords')
    op.drop_column('research_papers', 'submitted_date')
    op.drop_column('research_papers', 'research_type')
    op.drop_column('research_papers', 'abstract')
    op.drop_table('comments')
    op.drop_table('research_papers_status')
    # ### end Alembic commands ###
