"""revise

Revision ID: 42578a5a2278
Revises: 9eebbcaf847f
Create Date: 2023-11-02 10:17:40.154772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42578a5a2278'
down_revision: Union[str, None] = '9eebbcaf847f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    op.alter_column('research_papers', 'adviser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'research_papers', 'users', ['adviser_id'], ['id'])
    op.drop_column('research_papers', 'abstract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('abstract', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'research_papers', type_='foreignkey')
    op.alter_column('research_papers', 'adviser_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'name')
    # ### end Alembic commands ###
