"""edited tables

Revision ID: 46cc6cd3a040
Revises: 62963b8e1583
Create Date: 2023-11-01 18:20:50.034930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cc6cd3a040'
down_revision: Union[str, None] = '62963b8e1583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'name')
    op.add_column('research_papers', sa.Column('adviser_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_papers', 'adviser_id')
    op.add_column('authors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
