"""add more column

Revision ID: 4c48edc719fb
Revises: e5bcf6e05147
Create Date: 2023-12-26 16:39:42.504582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c48edc719fb'
down_revision: Union[str, None] = 'e5bcf6e05147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('section', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'section')
    # ### end Alembic commands ###
