"""new

Revision ID: 58c9a0d08e70
Revises: 3f78fd13d719
Create Date: 2023-11-09 10:08:32.619758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58c9a0d08e70'
down_revision: Union[str, None] = '3f78fd13d719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'authors', 'research_papers', ['research_paper_id'], ['id'])
    op.add_column('research_papers_status', sa.Column('research_paper_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'research_papers_status', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_papers_status', type_='foreignkey')
    op.drop_column('research_papers_status', 'research_paper_id')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    # ### end Alembic commands ###
