"""ethicsupdate

Revision ID: 5dd8d108239e
Revises: abea376e09f6
Create Date: 2023-11-23 10:55:53.292073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd8d108239e'
down_revision: Union[str, None] = 'abea376e09f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ethics', 'letter_of_intent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'urec_9',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'urec_10',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'urec_11',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'urec_12',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'certificate_of_validation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ethics', 'co_authorship',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ethics', 'co_authorship',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'certificate_of_validation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'urec_12',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'urec_11',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'urec_10',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'urec_9',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ethics', 'letter_of_intent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
