"""Isang bagsakan

Revision ID: 605dc15935ce
Revises: 610341c77e58
Create Date: 2024-01-11 20:29:21.063461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '605dc15935ce'
down_revision: Union[str, None] = '610341c77e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RISClass',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISannouncements',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_role_target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('announcement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('other_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISnavigation_role',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_submitted_proposal', sa.Boolean(), nullable=False),
    sa.Column('has_pre_oral_defense_date', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_ethics_protocol', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_full_manuscript', sa.Boolean(), nullable=False),
    sa.Column('has_set_final_defense_date', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_copyright', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RISnavigation_role_id'), 'RISnavigation_role', ['id'], unique=True)
    op.create_table('RISnavigation_class',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('navigation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['RISClass.id'], ),
    sa.ForeignKeyConstraint(['navigation_id'], ['RISnavigation_role.id'], ),
    sa.PrimaryKeyConstraint('id', 'navigation_id', 'class_id')
    )
    op.create_table('RISfaculty_research_papers',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISnotifications',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISresearch_types_assigned',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('research_type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISsection_assigned_prof',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['RISClass.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISworkflow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISsections_course_assigned',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['RISClass.id'], ),
    sa.ForeignKeyConstraint(['research_type_id'], ['RISresearch_types_assigned.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISworkflow_class',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['RISClass.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['RISworkflow.id'], ),
    sa.PrimaryKeyConstraint('id', 'workflow_id', 'class_id')
    )
    op.create_table('RISworkflow_steps',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['RISworkflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISresearch_papers',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_adviser', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['RISworkflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISauthors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RIScomments',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['RISUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RIScopyright',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('co_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affidavit_co_ownership', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joint_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_sheet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recordal_slip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acknowledgement_receipt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recordal_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ureb_18', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('journal_publication', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('copyright_manuscript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['RISworkflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISethics',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('letter_of_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urec_9', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urec_10', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urec_11', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urec_12', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_of_validation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('co_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['RISworkflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISfull_manuscript',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['RISworkflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RISresearch_defense',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['RISresearch_papers.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['RISworkflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
 

def downgrade() -> None:

    op.drop_table('RISresearch_defense')
    op.drop_table('RISfull_manuscript')
    op.drop_table('RISethics')
    op.drop_table('RIScopyright')
    op.drop_table('RIScomments')
    op.drop_table('RISauthors')
    op.drop_table('RISresearch_papers')
    op.drop_table('RISworkflow_steps')
    op.drop_table('RISworkflow_class')
    op.drop_table('RISsections_course_assigned')
    op.drop_table('RISworkflow')
    op.drop_table('RISsection_assigned_prof')
    op.drop_table('RISresearch_types_assigned')
    op.drop_table('RISnotifications')
    op.drop_table('RISfaculty_research_papers')
    op.drop_table('RISnavigation_class')
    op.drop_index(op.f('ix_RISnavigation_role_id'), table_name='RISnavigation_role')
    op.drop_table('RISnavigation_role')
    op.drop_table('RISannouncements')
    op.drop_table('RISClass')
    # ### end Alembic commands ###
