"""revise2

Revision ID: 6a420e03dbfc
Revises: 7d987de57da6
Create Date: 2023-11-11 16:42:16.270318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a420e03dbfc'
down_revision: Union[str, None] = '7d987de57da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_papers', 'research_papers_status', ['status_id'], ['id'])
    op.add_column('research_papers_status', sa.Column('research_paper_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_papers_status', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_papers_status', type_='foreignkey')
    op.drop_column('research_papers_status', 'research_paper_id')
    op.drop_constraint(None, 'research_papers', type_='foreignkey')
    op.drop_column('research_papers', 'status_id')
    # ### end Alembic commands ###
