"""research fk

Revision ID: 6ad0d84d2368
Revises: b0dec96a03f5
Create Date: 2023-11-29 12:26:17.672044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ad0d84d2368'
down_revision: Union[str, None] = 'b0dec96a03f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'research_papers', 'workflow_steps', ['workflow_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_papers', type_='foreignkey')
    op.drop_column('research_papers', 'workflow_step_id')
    # ### end Alembic commands ###
