"""relation2

Revision ID: 7d987de57da6
Revises: e697d6adb37c
Create Date: 2023-11-11 16:20:18.384459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d987de57da6'
down_revision: Union[str, None] = 'e697d6adb37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('research_papers_status_research_paper_id_fkey', 'research_papers_status', type_='foreignkey')
    op.drop_column('research_papers_status', 'research_paper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers_status', sa.Column('research_paper_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('research_papers_status_research_paper_id_fkey', 'research_papers_status', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###
