"""boom sabog na

Revision ID: 96b71376f35c
Revises: 947b9a13d61e
Create Date: 2023-12-18 23:21:17.474123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '96b71376f35c'
down_revision: Union[str, None] = '947b9a13d61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_role',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_submitted_proposal', sa.Boolean(), nullable=False),
    sa.Column('has_pre_oral_defense_date', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_ethics_protocol', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_full_manuscript', sa.Boolean(), nullable=False),
    sa.Column('has_set_final_defense_date', sa.Boolean(), nullable=False),
    sa.Column('has_submitted_copyright', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_for_step',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tab_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['process_for.id'], name='process_for_step_tab_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='process_for_step_pkey')
    )
    op.create_table('process_for',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='process_for_pkey')
    )
    op.drop_index(op.f('ix_navigation_role_id'), table_name='navigation_role')
    op.drop_table('navigation_role')
    # ### end Alembic commands ###
