"""time

Revision ID: a06acad0cd31
Revises: 2e649ede6f62
Create Date: 2024-01-07 13:58:53.788940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06acad0cd31'
down_revision: Union[str, None] = '2e649ede6f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_defense', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_defense', 'time')
    # ### end Alembic commands ###
