"""ethics

Revision ID: abea376e09f6
Revises: 3b2c00d0eb95
Create Date: 2023-11-20 15:24:21.249067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'abea376e09f6'
down_revision: Union[str, None] = '3b2c00d0eb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethics',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('letter_of_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urec_9', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urec_10', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urec_11', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urec_12', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_of_validation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('co_authorship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['research_paper_id'], ['research_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ethics')
    # ### end Alembic commands ###
