"""5th

Revision ID: b81faa3ece2e
Revises: d7ab97cad76b
Create Date: 2023-11-12 20:24:39.854227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b81faa3ece2e'
down_revision: Union[str, None] = 'd7ab97cad76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('authors', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('authors', 'research_paper_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('authors', 'modified_at')
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('authors', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('authors', 'research_paper_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
