"""8th

Revision ID: b840a4e78625
Revises: d24acb4da9ef
Create Date: 2023-11-14 21:56:27.797993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b840a4e78625'
down_revision: Union[str, None] = 'd24acb4da9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comments', sa.Column('research_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('comments_research_paper_status_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'research_papers', ['research_paper_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'research_paper_status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('research_paper_status_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_research_paper_status_id_fkey', 'comments', 'research_papers_status', ['research_paper_status_id'], ['id'])
    op.drop_column('comments', 'research_paper_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
