"""help

Revision ID: c5cbca0ec3d3
Revises: 58c9a0d08e70
Create Date: 2023-11-10 11:00:17.549670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cbca0ec3d3'
down_revision: Union[str, None] = '58c9a0d08e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_research_paper_id_fkey', 'authors', type_='foreignkey')
    op.drop_column('authors', 'research_paper_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('research_paper_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('authors_research_paper_id_fkey', 'authors', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###
