"""New

Revision ID: d456b7062b5f
Revises: b69c6f2271c3
Create Date: 2023-12-26 16:09:27.891643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd456b7062b5f'
down_revision: Union[str, None] = 'b69c6f2271c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    op.drop_column('student', 'course')
    op.drop_column('student', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('student_class')
    # ### end Alembic commands ###
