"""second connection

Revision ID: db7f186474b1
Revises: 6ad0d84d2368
Create Date: 2023-11-29 15:43:09.503490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'db7f186474b1'
down_revision: Union[str, None] = '6ad0d84d2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copyright', sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'copyright', 'workflow_steps', ['workflow_step_id'], ['id'])
    op.add_column('ethics', sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'ethics', 'workflow_steps', ['workflow_step_id'], ['id'])
    op.add_column('full_manuscript', sa.Column('workflow_step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'full_manuscript', 'workflow_steps', ['workflow_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'full_manuscript', type_='foreignkey')
    op.drop_column('full_manuscript', 'workflow_step_id')
    op.drop_constraint(None, 'ethics', type_='foreignkey')
    op.drop_column('ethics', 'workflow_step_id')
    op.drop_constraint(None, 'copyright', type_='foreignkey')
    op.drop_column('copyright', 'workflow_step_id')
    # ### end Alembic commands ###
