"""renamecolumns

Revision ID: e5bcf6e05147
Revises: d456b7062b5f
Create Date: 2023-12-26 16:37:12.676445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e5bcf6e05147'
down_revision: Union[str, None] = 'd456b7062b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('course', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('class', 'year')
    op.drop_column('class', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('class', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('class', 'course')
    # ### end Alembic commands ###
