"""edit of relationships

Revision ID: e655cd293de6
Revises: 3eb9b26b209b
Create Date: 2023-11-05 21:10:21.787967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e655cd293de6'
down_revision: Union[str, None] = '3eb9b26b209b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_research_paper_id_fkey', 'authors', type_='foreignkey')
    op.alter_column('research_papers', 'research_adviser',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_papers', 'research_adviser',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('authors_research_paper_id_fkey', 'authors', 'research_papers', ['research_paper_id'], ['id'])
    # ### end Alembic commands ###
