"""add abstract

Revision ID: e84dbab3d760
Revises: fc3dcb435552
Create Date: 2023-11-24 15:30:28.009551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e84dbab3d760'
down_revision: Union[str, None] = 'fc3dcb435552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('full_manuscript', sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('full_manuscript', 'abstract')
    # ### end Alembic commands ###
