"""include

Revision ID: ef3ad9972e66
Revises: fc1d33ac6dab
Create Date: 2024-01-03 19:37:36.890574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ef3ad9972e66'
down_revision: Union[str, None] = 'fc1d33ac6dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_class',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('navigation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['navigation_id'], ['navigation_role.id'], ),
    sa.PrimaryKeyConstraint('id', 'navigation_id', 'class_id')
    )
    op.drop_column('navigation_role', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navigation_role', sa.Column('class_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('navigation_class')
    # ### end Alembic commands ###
