"""revisions

Revision ID: f2ff00a00ec4
Revises: 7b3a04fea78d
Create Date: 2023-12-26 22:14:59.119270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2ff00a00ec4'
down_revision: Union[str, None] = '7b3a04fea78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_assigned_prof', sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'section_assigned_prof', 'class', ['class_id'], ['id'])
    op.drop_column('section_assigned_prof', 'section')
    op.drop_column('section_assigned_prof', 'course')
    op.add_column('sections_course_assigned', sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'sections_course_assigned', 'class', ['class_id'], ['id'])
    op.drop_column('sections_course_assigned', 'section')
    op.drop_column('sections_course_assigned', 'course')
    op.add_column('workflow', sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'workflow', 'class', ['class_id'], ['id'])
    op.drop_column('workflow', 'year')
    op.drop_column('workflow', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('workflow', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'class_id')
    op.add_column('sections_course_assigned', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sections_course_assigned', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sections_course_assigned', type_='foreignkey')
    op.drop_column('sections_course_assigned', 'class_id')
    op.add_column('section_assigned_prof', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('section_assigned_prof', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'section_assigned_prof', type_='foreignkey')
    op.drop_column('section_assigned_prof', 'class_id')
    # ### end Alembic commands ###
