"""delete number step

Revision ID: fc1d33ac6dab
Revises: 385251d877b0
Create Date: 2024-01-03 11:55:22.175470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1d33ac6dab'
down_revision: Union[str, None] = '385251d877b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'step_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
